### ISSUE TITLE
Set Up Database and Sequelize Configuration

### ISSUE THREAD

**Issue by AnamarisOrtiz** [amritank/bravissimo#8]
## Description:
Initialize the project and set up Sequelize to connect to the PostgreSQL database. Create migration files for the User and Appreciation models.

# Tasks

- [x] Initialize a new Node.js project.
- [x] Install necessary dependencies (express, sequelize, pg, pg-hstore, bcrypt, dotenv).
- [x] Configure Sequelize to connect to the PostgreSQL database.
- [x] Create migration files for the User and Appreciation models.
- [x] Apply migrations to update the database schema.

Acceptance Criteria:
Node.js project is initialized.
Dependencies are installed.
Sequelize is configured and connected to PostgreSQL.
Migration files for User and Appreciation models are created and applied.
